### ISSUE TITLE
This seems fishy

### ISSUE THREAD

**Issue by Imadeanaccountjustpostthis** [ivanyordanovgt/brawl-stars-bot#2]
Hello there, I see some red flags within this repo. This leads me to believe this is malware.
First and foremost. The explanation about why this program is safe just feels like it's trying way too hard to convince the user to believe this is legitimate software. Like, it literally admits to obfuscating the code. "Compilers and packaging tools often employ techniques like code obfuscation and packing to optimize performance" My brother in christ no converter or compiler with a good intention obfuscates for "performance", obfuscation is to make a program harder to reverse engineer, which is perfect for malware authors trying to stop analysis. Why do you try so hard to hide the inner workings of this program? Do you have something to hide?
Second of all, the lack of source code of this program. If this issue would get solved, people could tell if this is safe or not.
Third. (not sure of this but I wanted to include this) The files inside the data_images folder don't make sense. For example, enemy.png shows multiple brawlers in the screenshot, including an ally and a power cube box. If that's data, how would the "AI" tell which one is the enemy?
This whole thing seems like a scam to me.

**Comment by ivanyordanovgt** [comment]
1. I am not trying too hard to convince the user it's legitimate. The short explanation is all you need. It's 2-3 sentences. The long one is A.I. generated if someone would like to go more in depth on how it works.

2. I am hiding the code and trying to make it as hard as possible to reverse engineer because I am putting a lot of work into this and I want it to be mine product. Would you accuse Adobe products of including malware because they do the exact same things? Simply don't want scammers to rebrand it and sell it because a lot of people already are trying to do that.

3. This version in github does not use A.I.. The updated one is in the discord. The data images are the images which I used to get the color ranges for the first color matching algorithm (which again, no A.I.). I left them there because many people were asking me at first on how I did the color ranges and I just explained them and left the images I used so they can use them too.

In the discord there are over 2400 people and over 400 weekly users. You can join the discord and ask whoever you want if they have been infected with anything. If you have more questions let me know!

**Comment by ivanyordanovgt** [comment]
An update will be happening soon and will move the installation into the repo again. The version in the repo is 5 versions behind I think.

**Comment by Imadeanaccountjustpostthis** [comment]
https://www.virustotal.com/gui/file/76e645f1bea45481f130981871fb0a90563eef6664719e4c4aa9a8c367032f01?nocache=0 huh

**Comment by Imadeanaccountjustpostthis** [comment]
you may want to take a look at that

> https://www.virustotal.com/gui/file/76e645f1bea45481f130981871fb0a90563eef6664719e4c4aa9a8c367032f01?nocache=0 huh

you may want to take a look at that and tell me why is that how it is

**Comment by ivanyordanovgt** [comment]
Well the new version in the discord passes the virus scan without getting a single virus detected. Simply because the version in the github combines all the packages into one executable and a lot of them can be detected as a virus simply because they have access to a lot of important stuff. Download the latest version from discord and virus scan it ;). No, no. Actually. Get the latest version, see all the folders inside (all installed packages). Import them into a hello world program and convert it to .exe with Nuitka. You will see you will have the same detections.
